### ISSUE TITLE
Minimum Pygments version

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#10]
@felixfontein do you know why it's set to 2.6.1? ansible/ansible itself requires 2.4+ with a comment that this is the version having a necessary bugfix for YAML+Jinja.
Any reason we can't set this version too?

**Comment by felixfontein** [comment]
The only reason is that this version has some bugs in the YAML / YAML+Jinja (maybe both, maybe just one) fixed. I'd keep this requirement just to make sure nobody accidentally uses an older version for Ansible-related stuff :)

**Comment by felixfontein** [comment]
It probably was 2.4 and not 2.6, as you noticed.
