### ISSUE TITLE
Add Trove classifiers to the metadata

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#18]
The full list of available entries is present here https://pypi.org/classifiers.

I'd probably use `Development Status :: 6 - Mature`, `License :: OSI Approved :: BSD License`, `Intended Audience :: Developers`, `Programming Language :: Python :: 3 :: Only`. Maybe add something extra if I missed anything.

**Comment by felixfontein** [comment]
Poetry automatically sets the license and Python classifiers BTW.
