### ISSUE TITLE
Figure out the license

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#5]
It's currently messed up a bit:
1) The lexer seems to be BSD
2) ~Sphinx integration code says both GPL and BSD in the same module (comment vs var) but I don't see any reason for it to be different from the lexer because it is a thing that is supposed to be linked in various projects so I'd just keep BSD~ This is not relevant anymore.
3) The readme and the meta says GPL
4) The Python dist must contain the license file which is not only not bundled but is also missing from the repo

@felixfontein Let's figure out what we want to do with this and make it consistent.

**Comment by felixfontein** [comment]
I'm happy to use BSD for this project. All GPL references are mainly from when this was a part of antsibull. The few non-BSD lines in this repo were all written by me (IIRC) and I'm happy to relicense them :)

Does BSD sound good to you?

**Comment by webknjaz** [comment]
I think so but I'd prefer a 3-clause version because of the non-endorsement clause (which looks totally compatible with 2-clause). OTOH I don't have a strong opinion on this.

**Comment by felixfontein** [comment]
I don't mind switching to that one, but I have no idea on the legal aspects.

**Comment by webknjaz** [comment]
The way I see it the main difference is that one says "don't use our name trying to advertise your derivative product unless we allowed you to do so". Which is good for when that product is bad and you don't want it to be associated with your name.

**Comment by felixfontein** [comment]
I like having the additional clause, but I don't know whether we can just add them, since the original authors used BSD 2-clause and not BSD 3-clause.

**Comment by jamescassell** [comment]
For the main ansible project, we've made contributors go back and get approval w/ their legal departments to relicense from BSD-3 to BSD-2, which main ansible uses for the module_utils.

**Comment by webknjaz** [comment]
@jamescassell oh, I see. I must've misremembered I was sure that it was BSD-3-clause.

**Comment by felixfontein** [comment]
I also remembered BSD 3-clause, but it clearly is 2-clause: https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L3

**Comment by webknjaz** [comment]
> I also remembered BSD 3-clause, but it clearly is 2-clause: [https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py#L3](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py?rgh-link-date=2021-06-03T16%3A40%3A03Z#L3)

Yep, I also had to look it up after James' comment :)
