### ISSUE TITLE
Rename the project (again...)

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#7]
So since #1, it doesn't make sense to imply sphinx dependency in the name. Let's come up with something catching the essence of what we're doing here better.

How about `ansible-highlighter` or `ansible-pygments`, maybe..? I think I like the latter more. WDYT?

**Comment by webknjaz** [comment]
The only thing I insist on is having a dash in the repo name. This removes the confusion when the Python importable name which is also a folder on disk is named the same way. It's a DX thing that is often important if one's terminal shell only outputs the current folder name, not the path.

**Comment by felixfontein** [comment]
I also prefer dashes instead of underscores. I also prefer `ansible-pygments`. I'll ask @gundalow to rename the repo (and will then proceed renaming the things inside).

**Comment by webknjaz** [comment]
Apparently, I have this sort of access so I've done the rename.

**Comment by webknjaz** [comment]
Feel free to proceed with moving the files around and adjusting meta+readme.

**Comment by felixfontein** [comment]
Thanks! Will do that later today.

**Comment by webknjaz** [comment]
I'll auto-replace things myself since I'm looking into it now.
