### ISSUE TITLE
Drop py2 compat boilerplate

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#8]
There's a number of things like "coding" and future imports that are simply unnecessary if we only care about py3 as stated by the dist metadata.
OTOH for as long as we don't use py3 only features, it could be reasonable to relax that requirement (assuming that the maintenance burden is low).

**Comment by felixfontein** [comment]
Since Python 2 is EOL anyway, I don't mind not supporting it.

**Comment by webknjaz** [comment]
Yep, I have the same opinion. But I usually support lower versions if that doesn't cause extra work. Basically, trying to balance maintenance burden vs not caring about ancient stuff.
