### ISSUE TITLE
Should Sphinx 4 compat lexer init omit the extra arg

### ISSUE THREAD

**Issue by webknjaz** [ansible-community/ansible-pygments#9]
Looking at https://github.com/ansible-community/sphinx_ansible_theme/commit/bd6b072bf0500c7c225a783857fef44f6781b0c2, I'm concerned about losing that `startinline=True` and so I looked up what sphinx itself does.
Turns out that they just use `functools.partial()` to bake in some initializer arg defaults: https://github.com/sphinx-doc/sphinx/blob/82dad44/sphinx/highlighting.py#L35-L43.

@felixfontein I'm wondering if that argument is essential to us in any way. And if so — why don't we apply the same approach. WDYT?

**Comment by webknjaz** [comment]
Looking at https://github.com/pygments/pygments/blame/1b966038502c0b386a6645d4b5125f623d0947bb/pygments/lexers/data.py, it doesn't seem to be used anywhere. But I just thought maybe you'd remember something about it. If not, feel free to close this issue.

**Comment by webknjaz** [comment]
I discovered that it's actually unnecessary to have a Sphinx extension manually registering the lexer since it gets picked up by Pygments automatically: https://github.com/ansible-community/sphinx_ansible_theme/commit/74034f7943b154736604e461b7bfbebeadbe6e6e. So instead I'll be looking into just dropping that and Sphinx from the deps.

**Comment by felixfontein** [comment]
I think this argument is not needed, which is why I removed it both in https://github.com/ansible/ansible/pull/74798 and https://github.com/ansible-community/antsibull/pull/273. I couldn't find any difference both during testing and reviewing Pygment's code.

**Comment by webknjaz** [comment]
@felixfontein yep, I've also inspected their repo and the only mention of it was in the PHP lexer. I've checked the inheritance chain and haven't seen anything related either.
